import at from './at/index';
import head from './at/head/index';
import tail from './at/tail/index';
import atRight from './at/right/index';
import averageBy from './average/by/index';
import averageOf from './average/of/index';
import concat from './concat/index';
import countOf from './count/of/index';
import countBy from './count/by/index';
import map from './map/index';
import fill from './fill/index';
import fillFull from './fill/full/index';
import fillStart from './fill/start/index';
import fillEnd from './fill/end/index';
import filter from './filter/index';
import find from './find/index';
import findRight from './find/right/index';
import findIndex from './find/index/index';
import findIndexRight from './find/index/right/index';
import forEach from './forEach/index';
import forEachRight from './forEach/right/index';
import groupBy from './groupBy/index';
import indexOf from './indexOf/index';
import lastIndexOf from './indexOf/last/index';
import isEmpty from './is/empty/index';
import join from './join/index';
import joinUp from './join/up/index';
import joinBy from './join/by/index';
import keyBy from './keyBy/index';
import limit from './limit/index';
import maximumBy from './maximum/by/index';
import maximumOf from './maximum/of/index';
import minimumBy from './minimum/by/index';
import minimumOf from './minimum/of/index';
import partition from './partition/index';
import reduce from './reduce/index';
import reduceRight from './reduce/right/index';
declare const array: ArrayConstructor & {
    at: typeof at;
    head: typeof head;
    tail: typeof tail;
    atRight: typeof atRight;
    averageBy: typeof averageBy;
    averageOf: typeof averageOf;
    concat: typeof concat;
    countOf: typeof countOf;
    countBy: typeof countBy;
    map: typeof map;
    fill: typeof fill;
    fillFull: typeof fillFull;
    fillStart: typeof fillStart;
    fillEnd: typeof fillEnd;
    filter: typeof filter;
    find: typeof find;
    findRight: typeof findRight;
    findIndex: typeof findIndex;
    findIndexRight: typeof findIndexRight;
    forEach: typeof forEach;
    forEachRight: typeof forEachRight;
    groupBy: typeof groupBy;
    indexOf: typeof indexOf;
    lastIndexOf: typeof lastIndexOf;
    isEmpty: typeof isEmpty;
    join: typeof join;
    joinUp: typeof joinUp;
    joinBy: typeof joinBy;
    keyBy: typeof keyBy;
    limit: typeof limit;
    maximumBy: typeof maximumBy;
    maximumOf: typeof maximumOf;
    minimumBy: typeof minimumBy;
    minimumOf: typeof minimumOf;
    partition: typeof partition;
    reduce: typeof reduce;
    reduceRight: typeof reduceRight;
};
export default array;
